version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: SecretPassword
      POSTGRES_DB: yams
      POSTGRES_USER: yams
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: SecretPassword
      POSTGRES_DB: yams
      POSTGRES_USER: yams
    ports:
      - "15432:5432"

  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3.7-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'docker.io/bitnami/kafka:3-debian-10'
    ports:
      - '9092:9092'
      - '9094:9094'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_HOST_NAME: localhost
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_HEAP_OPTS: -Xms1024m -Xms1024m
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local